# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ../SGP+JCA/data/NTU-RGB-D/xsub/val_data.npy
  label_path: ../SGP+JCA/data/NTU-RGB-D/xsub/val_label.pkl
  vel: True

# model
model: model.sgp_jca.Model
model_args:
  num_class: 60
  in_channels: 3
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d_sgp.Graph
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True

# test
phase: test
device: [0,1,2,3]
test_batch_size: 64




